/**
 * 2026 PGA Championship — Pre-set Tier Assignments
 *
 * LOCKED: 2026-05-18T14:55:24.450Z
 *
 * Auto-generated by scripts/build-field.js from ESPN event 401811947
 * and the OWGR snapshot in src/lib/owgr.json (generated 2026-05-18T14:45:30.036Z).
 *
 * ⚠️  Tier tables are LOCKED at generation time. Once this file exists,
 *     re-running build-field will refuse unless you pass --force. This
 *     keeps every pool member picking from the same set of options, no
 *     matter when they make their picks.
 *
 *     Refresh OWGR weekly with `npm run sync-owgr` — that's separate
 *     from this lock and only affects FUTURE build-field runs.
 *
 * Tier 1 (pick 1): OWGR  1–10   — Elite
 * Tier 2 (pick 2): OWGR 11–25   — Contenders
 * Tier 3 (pick 2): OWGR 26–50   — Mid-tier
 * Tier 4 (pick 1): OWGR 51+ / unranked (club pros, invites, etc.)
 */

import type { TierEntry } from "./tiers";

// ─── TIER 1 — OWGR 1-10 ────────────────────────────────────────────────
export const TIER_1: TierEntry[] = [
  { espnId: "9478"    , name: "Scottie Scheffler"                 , owgr: 1 },
  { espnId: "3470"    , name: "Rory McIlroy"                      , owgr: 2 },
  { espnId: "4425906" , name: "Cameron Young"                     , owgr: 3 },
  { espnId: "9037"    , name: "Matt Fitzpatrick"                  , owgr: 4 },
  { espnId: "569"     , name: "Justin Rose"                       , owgr: 5 },
  { espnId: "10592"   , name: "Collin Morikawa"                   , owgr: 6 },
  { espnId: "5539"    , name: "Tommy Fleetwood"                   , owgr: 7 },
  { espnId: "10140"   , name: "Xander Schauffele"                 , owgr: 8 },
  { espnId: "10166"   , name: "J.J. Spaun"                        , owgr: 9 },
  { espnId: "4690755" , name: "Chris Gotterup"                    , owgr: 10 },
];

// ─── TIER 2 — OWGR 11-25 ───────────────────────────────────────────────
export const TIER_2: TierEntry[] = [
  { espnId: "5409"    , name: "Russell Henley"                    , owgr: 11 },
  { espnId: "9780"    , name: "Jon Rahm"                          , owgr: 12 },
  { espnId: "4375972" , name: "Ludvig Åberg"                      , owgr: 13 },
  { espnId: "11378"   , name: "Robert MacIntyre"                  , owgr: 14 },
  { espnId: "10906"   , name: "Aaron Rai"                         , owgr: 15 },
  { espnId: "4848"    , name: "Justin Thomas"                     , owgr: 16 },
  { espnId: "4404992" , name: "Ben Griffin"                       , owgr: 17 },
  { espnId: "8961"    , name: "Sepp Straka"                       , owgr: 18 },
  { espnId: "5860"    , name: "Hideki Matsuyama"                  , owgr: 19 },
  { espnId: "3832"    , name: "Alex Noren"                        , owgr: 20 },
  { espnId: "5579"    , name: "Patrick Reed"                      , owgr: 21 },
  { espnId: "5408"    , name: "Harris English"                    , owgr: 22 },
  { espnId: "5054388" , name: "Jacob Bridgeman"                   , owgr: 23 },
  { espnId: "7081"    , name: "Si Woo Kim"                        , owgr: 24 },
  { espnId: "4348470" , name: "Kristoffer Reitan"                 , owgr: 25 },
];

// ─── TIER 3 — OWGR 26-50 ───────────────────────────────────────────────
export const TIER_3: TierEntry[] = [
  { espnId: "4419142" , name: "Akshay Bhatia"                     , owgr: 26 },
  { espnId: "5553"    , name: "Tyrrell Hatton"                    , owgr: 27 },
  { espnId: "11250"   , name: "Nicolai Højgaard"                  , owgr: 28 },
  { espnId: "10364"   , name: "Kurt Kitayama"                     , owgr: 29 },
  { espnId: "4364873" , name: "Viktor Hovland"                    , owgr: 30 },
  { espnId: "4410932" , name: "Min Woo Lee"                       , owgr: 31 },
  { espnId: "10046"   , name: "Bryson DeChambeau"                 , owgr: 32 },
  { espnId: "6007"    , name: "Patrick Cantlay"                   , owgr: 33 },
  { espnId: "9530"    , name: "Maverick McNealy"                  , owgr: 34 },
  { espnId: "9938"    , name: "Sam Burns"                         , owgr: 35 },
  { espnId: "4513"    , name: "Keegan Bradley"                    , owgr: 36 },
  { espnId: "5076021" , name: "Ryan Gerard"                       , owgr: 37 },
  { espnId: "3702"    , name: "Rickie Fowler"                     , owgr: 38 },
  { espnId: "4587"    , name: "Shane Lowry"                       , owgr: 40 },
  { espnId: "1680"    , name: "Jason Day"                         , owgr: 41 },
  { espnId: "9484"    , name: "Alex Smalley"                      , owgr: 42 },
  { espnId: "4585549" , name: "Marco Penge"                       , owgr: 43 },
  { espnId: "9025"    , name: "Daniel Berger"                     , owgr: 44 },
  { espnId: "8974"    , name: "Michael Kim"                       , owgr: 45 },
  { espnId: "4901368" , name: "Matt McCarty"                      , owgr: 46 },
  { espnId: "5467"    , name: "Jordan Spieth"                     , owgr: 47 },
  { espnId: "3550"    , name: "Gary Woodland"                     , owgr: 48 },
  { espnId: "388"     , name: "Adam Scott"                        , owgr: 49 },
  { espnId: "4408316" , name: "Nico Echavarria"                   , owgr: 50 },
];

// ─── TIER 4 — OWGR 51+ / unranked ──────────────────────────────────────
export const TIER_4: TierEntry[] = [
  { espnId: "4426181" , name: "Sam Stevens"                       , owgr: 51 },
  { espnId: "9126"    , name: "Corey Conners"                     , owgr: 52 },
  { espnId: "11332"   , name: "Andrew Novak"                      , owgr: 53 },
  { espnId: "4251"    , name: "Ryan Fox"                          , owgr: 54 },
  { espnId: "1225"    , name: "Brian Harman"                      , owgr: 55 },
  { espnId: "4921329" , name: "Michael Brennan"                   , owgr: 56 },
  { espnId: "4837368" , name: "Pierceson Coody"                   , owgr: 57 },
  { espnId: "4895429" , name: "David Puig"                        , owgr: 58 },
  { espnId: "3792"    , name: "Nick Taylor"                       , owgr: 59 },
  { espnId: "4858572" , name: "Ryo Hisatsune"                     , owgr: 60 },
  { espnId: "4589438" , name: "Harry Hall"                        , owgr: 61 },
  { espnId: "4585548" , name: "Sami Välimäki"                     , owgr: 62 },
  { espnId: "11101"   , name: "Max Greyserman"                    , owgr: 63 },
  { espnId: "4837"    , name: "Thomas Detry"                      , owgr: 64 },
  { espnId: "4566443" , name: "Matti Schmid"                      , owgr: 65 },
  { espnId: "5338"    , name: "Bud Cauley"                        , owgr: 66 },
  { espnId: "11253"   , name: "Rasmus Højgaard"                   , owgr: 67 },
  { espnId: "4604053" , name: "Jayden Schaper"                    , owgr: 68 },
  { espnId: "10548"   , name: "Matt Wallace"                      , owgr: 69 },
  { espnId: "4425904" , name: "Michael Thorbjornsen"              , owgr: 70 },
  { espnId: "9506"    , name: "Jordan Smith"                      , owgr: 71 },
  { espnId: "11382"   , name: "Sungjae Im"                        , owgr: 72 },
  { espnId: "4610056" , name: "Casey Jarvis"                      , owgr: 73 },
  { espnId: "5080439" , name: "Aldrich Potgieter"                 , owgr: 74 },
  { espnId: "11119"   , name: "Wyndham Clark"                     , owgr: 75 },
  { espnId: "6825"    , name: "Patrick Rodgers"                   , owgr: 76 },
  { espnId: "5217048" , name: "Johnny Keefer"                     , owgr: 77 },
  { espnId: "10980"   , name: "Sahith Theegala"                   , owgr: 78 },
  { espnId: "4858859" , name: "Rasmus Neergaard-Petersen"         , owgr: 79 },
  { espnId: "9221"    , name: "Haotong Li"                        , owgr: 80 },
  { espnId: "5502"    , name: "Andrew Putnam"                     , owgr: 81 },
  { espnId: "9658"    , name: "Taylor Pendrith"                   , owgr: 82 },
  { espnId: "4364865" , name: "Alex Fitzpatrick"                  , owgr: 83 },
  { espnId: "11383"   , name: "Max McGreevy"                      , owgr: 84 },
  { espnId: "10505"   , name: "J.T. Poston"                       , owgr: 85 },
  { espnId: "4671"    , name: "John Parry"                        , owgr: 86 },
  { espnId: "11056"   , name: "Austin Smotherman"                 , owgr: 87 },
  { espnId: "9243"    , name: "Christiaan Bezuidenhout"           , owgr: 88 },
  { espnId: "11385"   , name: "Rico Hoey"                         , owgr: 89 },
  { espnId: "4425899" , name: "Daniel Hillier"                    , owgr: 91 },
  { espnId: "4691931" , name: "Ricky Castillo"                    , owgr: 92 },
  { espnId: "6937"    , name: "Stephan Jaeger"                    , owgr: 93 },
  { espnId: "11393"   , name: "Garrick Higgo"                     , owgr: 94 },
  { espnId: "6701"    , name: "David Lipsky"                      , owgr: 95 },
  { espnId: "3449"    , name: "Chris Kirk"                        , owgr: 96 },
  { espnId: "676"     , name: "Lucas Glover"                      , owgr: 97 },
  { espnId: "10054"   , name: "Denny McCarthy"                    , owgr: 98 },
  { espnId: "4714133" , name: "Elvis Smylie"                      , owgr: 100 },
  { espnId: "6962"    , name: "Adrien Saddier"                    , owgr: 101 },
  { espnId: "1407"    , name: "Daniel Brown"                      , owgr: 102 },
  { espnId: "4618114" , name: "Chandler Blanchet"                 , owgr: 103 },
  { espnId: "9525"    , name: "Brian Campbell"                    , owgr: 104 },
  { espnId: "5143175" , name: "Sudarshan Yellamaraju"             , owgr: 106 },
  { espnId: "5956"    , name: "Andy Sullivan"                     , owgr: 107 },
  { espnId: "8906"    , name: "Keith Mitchell"                    , owgr: 108 },
  { espnId: "5105333" , name: "Angel Ayora"                       , owgr: 109 },
  { espnId: "6086"    , name: "Tom Hoge"                          , owgr: 110 },
  { espnId: "6798"    , name: "Brooks Koepka"                     , owgr: 111 },
  { espnId: "5882"    , name: "Emiliano Grillo"                   , owgr: 117 },
  { espnId: "4348444" , name: "Tom McKibbin"                      , owgr: 119 },
  { espnId: "4408324" , name: "Ian Holt"                          , owgr: 121 },
  { espnId: "1030"    , name: "Jhonattan Vegas"                   , owgr: 122 },
  { espnId: "1651"    , name: "Billy Horschel"                    , owgr: 123 },
  { espnId: "8973"    , name: "Max Homa"                          , owgr: 124 },
  { espnId: "5076025" , name: "William Mouw"                      , owgr: 129 },
  { espnId: "4699290" , name: "Mikael Lindberg"                   , owgr: 133 },
  { espnId: "1222"    , name: "Brandt Snedeker"                   , owgr: 134 },
  { espnId: "4426182" , name: "Steven Fisk"                       , owgr: 135 },
  { espnId: "11099"   , name: "Joaquín Niemann"                   , owgr: 143 },
  { espnId: "9131"    , name: "Cameron Smith"                     , owgr: 145 },
  { espnId: "11345"   , name: "Travis Smyth"                      , owgr: 147 },
  { espnId: "10058"   , name: "Davis Riley"                       , owgr: 151 },
  { espnId: "4597553" , name: "Kazuki Higa"                       , owgr: 153 },
  { espnId: "4868733" , name: "Joe Highsmith"                     , owgr: 155 },
  { espnId: "10372"   , name: "Adam Schenk"                       , owgr: 158 },
  { espnId: "5312609" , name: "Kota Kaneko"                       , owgr: 192 },
  { espnId: "5070301" , name: "Austin Hurt"                       , owgr: 999 },
  { espnId: "4372513" , name: "Ben Kern"                          , owgr: 999 },
  { espnId: "10179"   , name: "Ben Polland"                       , owgr: 999 },
  { espnId: "4317"    , name: "Bernd Wiesberger"                  , owgr: 999 },
  { espnId: "5145292" , name: "Braden Shattuck"                   , owgr: 999 },
  { espnId: "2233"    , name: "Bryce Fisher"                      , owgr: 999 },
  { espnId: "5350613" , name: "Chris Gabriele"                    , owgr: 999 },
  { espnId: "5350614" , name: "Derek Berg"                        , owgr: 999 },
  { espnId: "3448"    , name: "Dustin Johnson"                    , owgr: 999 },
  { espnId: "3089127" , name: "Francisco Bidé"                    , owgr: 999 },
  { espnId: "5921"    , name: "Garrett Sapp"                      , owgr: 999 },
  { espnId: "5070304" , name: "Jared Jones"                       , owgr: 999 },
  { espnId: "110"     , name: "Jason Dufner"                      , owgr: 999 },
  { espnId: "11481"   , name: "Jesse Droemer"                     , owgr: 999 },
  { espnId: "446"     , name: "Jimmy Walker"                      , owgr: 999 },
  { espnId: "11243"   , name: "Jordan Gumberg"                    , owgr: 999 },
  { espnId: "601"     , name: "Luke Donald"                       , owgr: 999 },
  { espnId: "4845304" , name: "Mark Geddes"                       , owgr: 999 },
  { espnId: "3670"    , name: "Martin Kaymer"                     , owgr: 999 },
  { espnId: "3312"    , name: "Michael Block"                     , owgr: 999 },
  { espnId: "4693951" , name: "Michael Kartrude"                  , owgr: 999 },
  { espnId: "186"     , name: "Padraig Harrington"                , owgr: 999 },
  { espnId: "5350615" , name: "Paul McClure"                      , owgr: 999 },
  { espnId: "9620"    , name: "Ryan Lenahan"                      , owgr: 999 },
  { espnId: "3284"    , name: "Ryan Vermeer"                      , owgr: 999 },
  { espnId: "307"     , name: "Shaun Micheel"                     , owgr: 999 },
  { espnId: "78"      , name: "Stewart Cink"                      , owgr: 999 },
  { espnId: "4349544" , name: "Timothy Wiseman"                   , owgr: 999 },
  { espnId: "4723205" , name: "Tyler Collet"                      , owgr: 999 },
  { espnId: "1350"    , name: "Y.E. Yang"                         , owgr: 999 },
  { espnId: "5350616" , name: "Zach Haynes"                       , owgr: 999 },
];

// ─── Lookup helpers ─────────────────────────────────────────────────────

const tierLookup: Map<string, number> = new Map();
for (const g of TIER_1) tierLookup.set(g.espnId, 1);
for (const g of TIER_2) tierLookup.set(g.espnId, 2);
for (const g of TIER_3) tierLookup.set(g.espnId, 3);
for (const g of TIER_4) tierLookup.set(g.espnId, 4);

const owgrLookup: Map<string, number> = new Map();
for (const tier of [TIER_1, TIER_2, TIER_3, TIER_4]) {
  for (const g of tier) owgrLookup.set(g.espnId, g.owgr);
}

export function getTierForGolfer(espnId: string): number {
  return tierLookup.get(espnId) ?? 4;
}

export function getOwgrForGolfer(espnId: string): number {
  return owgrLookup.get(espnId) ?? 999;
}

export function getAllPgaPlayerIds(): Set<string> {
  return new Set(
    [...TIER_1, ...TIER_2, ...TIER_3, ...TIER_4].map((g) => g.espnId)
  );
}
