/**
 * 2026 U.S. Open — Pre-set Tier Assignments
 *
 * LOCKED: 2026-06-19T17:14:20.958Z
 *
 * Auto-generated by scripts/build-field.js from ESPN event 401811952
 * and the OWGR snapshot in src/lib/owgr.json (generated 2026-06-19T17:13:37.842Z).
 *
 * ⚠️  Tier tables are LOCKED at generation time. Once this file exists,
 *     re-running build-field will refuse unless you pass --force. This
 *     keeps every pool member picking from the same set of options, no
 *     matter when they make their picks.
 *
 *     Refresh OWGR weekly with `npm run sync-owgr` — that's separate
 *     from this lock and only affects FUTURE build-field runs.
 *
 * Tier 1 (pick 1): OWGR  1–10   — Elite
 * Tier 2 (pick 2): OWGR 11–25   — Contenders
 * Tier 3 (pick 2): OWGR 26–50   — Mid-tier
 * Tier 4 (pick 1): OWGR 51+ / unranked (club pros, invites, etc.)
 */

import type { TierEntry } from "./tiers";

// ─── TIER 1 — OWGR 1-10 ────────────────────────────────────────────────
export const TIER_1: TierEntry[] = [
  { espnId: "9478"    , name: "Scottie Scheffler"                 , owgr: 1 },
  { espnId: "3470"    , name: "Rory McIlroy"                      , owgr: 2 },
  { espnId: "4425906" , name: "Cameron Young"                     , owgr: 3 },
  { espnId: "9037"    , name: "Matt Fitzpatrick"                  , owgr: 4 },
  { espnId: "5409"    , name: "Russell Henley"                    , owgr: 5 },
  { espnId: "5539"    , name: "Tommy Fleetwood"                   , owgr: 6 },
  { espnId: "569"     , name: "Justin Rose"                       , owgr: 7 },
  { espnId: "9780"    , name: "Jon Rahm"                          , owgr: 8 },
  { espnId: "10166"   , name: "J.J. Spaun"                        , owgr: 9 },
  { espnId: "10592"   , name: "Collin Morikawa"                   , owgr: 10 },
];

// ─── TIER 2 — OWGR 11-25 ───────────────────────────────────────────────
export const TIER_2: TierEntry[] = [
  { espnId: "4690755" , name: "Chris Gotterup"                    , owgr: 11 },
  { espnId: "10140"   , name: "Xander Schauffele"                 , owgr: 12 },
  { espnId: "4375972" , name: "Ludvig Åberg"                      , owgr: 13 },
  { espnId: "10906"   , name: "Aaron Rai"                         , owgr: 14 },
  { espnId: "4404992" , name: "Ben Griffin"                       , owgr: 15 },
  { espnId: "4848"    , name: "Justin Thomas"                     , owgr: 16 },
  { espnId: "11378"   , name: "Robert MacIntyre"                  , owgr: 17 },
  { espnId: "7081"    , name: "Si Woo Kim"                        , owgr: 18 },
  { espnId: "8961"    , name: "Sepp Straka"                       , owgr: 19 },
  { espnId: "3832"    , name: "Alex Noren"                        , owgr: 20 },
  { espnId: "5553"    , name: "Tyrrell Hatton"                    , owgr: 21 },
  { espnId: "5408"    , name: "Harris English"                    , owgr: 22 },
  { espnId: "5076021" , name: "Ryan Gerard"                       , owgr: 23 },
  { espnId: "5860"    , name: "Hideki Matsuyama"                  , owgr: 24 },
  { espnId: "5054388" , name: "Jacob Bridgeman"                   , owgr: 25 },
];

// ─── TIER 3 — OWGR 26-50 ───────────────────────────────────────────────
export const TIER_3: TierEntry[] = [
  { espnId: "4348470" , name: "Kristoffer Reitan"                 , owgr: 26 },
  { espnId: "5579"    , name: "Patrick Reed"                      , owgr: 27 },
  { espnId: "4364873" , name: "Viktor Hovland"                    , owgr: 28 },
  { espnId: "4419142" , name: "Akshay Bhatia"                     , owgr: 29 },
  { espnId: "9938"    , name: "Sam Burns"                         , owgr: 30 },
  { espnId: "10364"   , name: "Kurt Kitayama"                     , owgr: 31 },
  { espnId: "10046"   , name: "Bryson DeChambeau"                 , owgr: 32 },
  { espnId: "11250"   , name: "Nicolai Højgaard"                  , owgr: 33 },
  { espnId: "11119"   , name: "Wyndham Clark"                     , owgr: 34 },
  { espnId: "4410932" , name: "Min Woo Lee"                       , owgr: 35 },
  { espnId: "6007"    , name: "Patrick Cantlay"                   , owgr: 36 },
  { espnId: "9530"    , name: "Maverick McNealy"                  , owgr: 37 },
  { espnId: "10505"   , name: "J.T. Poston"                       , owgr: 38 },
  { espnId: "4513"    , name: "Keegan Bradley"                    , owgr: 39 },
  { espnId: "5338"    , name: "Bud Cauley"                        , owgr: 40 },
  { espnId: "3702"    , name: "Rickie Fowler"                     , owgr: 41 },
  { espnId: "9484"    , name: "Alex Smalley"                      , owgr: 42 },
  { espnId: "9843"    , name: "Jake Knapp"                        , owgr: 43 },
  { espnId: "4587"    , name: "Shane Lowry"                       , owgr: 44 },
  { espnId: "3550"    , name: "Gary Woodland"                     , owgr: 45 },
  { espnId: "9025"    , name: "Daniel Berger"                     , owgr: 46 },
  { espnId: "1680"    , name: "Jason Day"                         , owgr: 47 },
  { espnId: "388"     , name: "Adam Scott"                        , owgr: 49 },
  { espnId: "8974"    , name: "Michael Kim"                       , owgr: 50 },
];

// ─── TIER 4 — OWGR 51+ / unranked ──────────────────────────────────────
export const TIER_4: TierEntry[] = [
  { espnId: "5467"    , name: "Jordan Spieth"                     , owgr: 51 },
  { espnId: "4408316" , name: "Nico Echavarria"                   , owgr: 52 },
  { espnId: "4901368" , name: "Matt McCarty"                      , owgr: 53 },
  { espnId: "4426181" , name: "Sam Stevens"                       , owgr: 54 },
  { espnId: "4251"    , name: "Ryan Fox"                          , owgr: 55 },
  { espnId: "9126"    , name: "Corey Conners"                     , owgr: 56 },
  { espnId: "4895429" , name: "David Puig"                        , owgr: 57 },
  { espnId: "4837368" , name: "Pierceson Coody"                   , owgr: 58 },
  { espnId: "1225"    , name: "Brian Harman"                      , owgr: 59 },
  { espnId: "4921329" , name: "Michael Brennan"                   , owgr: 60 },
  { espnId: "11332"   , name: "Andrew Novak"                      , owgr: 61 },
  { espnId: "4858572" , name: "Ryo Hisatsune"                     , owgr: 62 },
  { espnId: "3792"    , name: "Nick Taylor"                       , owgr: 63 },
  { espnId: "4589438" , name: "Harry Hall"                        , owgr: 66 },
  { espnId: "11101"   , name: "Max Greyserman"                    , owgr: 68 },
  { espnId: "4364865" , name: "Alex Fitzpatrick"                  , owgr: 69 },
  { espnId: "4604053" , name: "Jayden Schaper"                    , owgr: 70 },
  { espnId: "4566443" , name: "Matti Schmid"                      , owgr: 71 },
  { espnId: "11382"   , name: "Sungjae Im"                        , owgr: 74 },
  { espnId: "5217048" , name: "Johnny Keefer"                     , owgr: 75 },
  { espnId: "11099"   , name: "Joaquín Niemann"                   , owgr: 80 },
  { espnId: "6825"    , name: "Patrick Rodgers"                   , owgr: 81 },
  { espnId: "10980"   , name: "Sahith Theegala"                   , owgr: 83 },
  { espnId: "5502"    , name: "Andrew Putnam"                     , owgr: 85 },
  { espnId: "10343"   , name: "Lucas Herbert"                     , owgr: 88 },
  { espnId: "5143175" , name: "Sudarshan Yellamaraju"             , owgr: 96 },
  { espnId: "11383"   , name: "Max McGreevy"                      , owgr: 99 },
  { espnId: "8906"    , name: "Keith Mitchell"                    , owgr: 100 },
  { espnId: "4671"    , name: "John Parry"                        , owgr: 102 },
  { espnId: "3449"    , name: "Chris Kirk"                        , owgr: 106 },
  { espnId: "6798"    , name: "Brooks Koepka"                     , owgr: 110 },
  { espnId: "6962"    , name: "Adrien Saddier"                    , owgr: 115 },
  { espnId: "5882"    , name: "Emiliano Grillo"                   , owgr: 116 },
  { espnId: "4982182" , name: "Jackson Suber"                     , owgr: 128 },
  { espnId: "5076025" , name: "William Mouw"                      , owgr: 131 },
  { espnId: "4408320" , name: "Kevin Roy"                         , owgr: 133 },
  { espnId: "1651"    , name: "Billy Horschel"                    , owgr: 135 },
  { espnId: "9131"    , name: "Cameron Smith"                     , owgr: 136 },
  { espnId: "4602218" , name: "Davis Thompson"                    , owgr: 138 },
  { espnId: "4602673" , name: "Tom Kim"                           , owgr: 141 },
  { espnId: "5550"    , name: "Laurie Canter"                     , owgr: 151 },
  { espnId: "5076011" , name: "Adrien Dumont de Chassart"         , owgr: 168 },
  { espnId: "4587989" , name: "Chandler Phillips"                 , owgr: 172 },
  { espnId: "1674"    , name: "Peter Uihlein"                     , owgr: 181 },
  { espnId: "6922"    , name: "Ben Kohles"                        , owgr: 184 },
  { espnId: "9899"    , name: "Hennie Du Plessis"                 , owgr: 186 },
  { espnId: "5532"    , name: "Carlos Ortiz"                      , owgr: 188 },
  { espnId: "5209442" , name: "Neal Shipley"                      , owgr: 190 },
  { espnId: "4358081" , name: "Alejandro Tosti"                   , owgr: 999 },
  { espnId: "11469"   , name: "Angel Hidalgo"                     , owgr: 999 },
  { espnId: "5362524" , name: "Arni Sveinsson"                    , owgr: 999 },
  { espnId: "5077389" , name: "Ben James"                         , owgr: 999 },
  { espnId: "8910"    , name: "Ben Silverman"                     , owgr: 999 },
  { espnId: "2201886" , name: "Brandon Holtz"                     , owgr: 999 },
  { espnId: "4355673" , name: "Brandon Wu"                        , owgr: 999 },
  { espnId: "5289813" , name: "Bryan Lee"                         , owgr: 999 },
  { espnId: "5110034" , name: "Caleb Surratt"                     , owgr: 999 },
  { espnId: "9951"    , name: "Carl Yuan"                         , owgr: 999 },
  { espnId: "5362520" , name: "Chase Kyes"                        , owgr: 999 },
  { espnId: "10047"   , name: "Cole Hammer"                       , owgr: 999 },
  { espnId: "5027437" , name: "Cooper Dossey"                     , owgr: 999 },
  { espnId: "3448"    , name: "Dustin Johnson"                    , owgr: 999 },
  { espnId: "4423323" , name: "Dylan Wu"                          , owgr: 999 },
  { espnId: "5362521" , name: "Eric Lee"                          , owgr: 999 },
  { espnId: "5293232" , name: "Ethan Fang"                        , owgr: 999 },
  { espnId: "4884239" , name: "Filippo Celli"                     , owgr: 999 },
  { espnId: "5272338" , name: "Giuseppe Puebla"                   , owgr: 999 },
  { espnId: "301"     , name: "Graeme McDowell"                   , owgr: 999 },
  { espnId: "5327840" , name: "Greyson Leach"                     , owgr: 999 },
  { espnId: "5343786" , name: "Hamilton Coleman"                  , owgr: 999 },
  { espnId: "4844"    , name: "Harry Higgs"                       , owgr: 999 },
  { espnId: "1067"    , name: "J.B. Holmes"                       , owgr: 999 },
  { espnId: "5362526" , name: "Jack Schoenberger"                 , owgr: 999 },
  { espnId: "5344766" , name: "Jackson Herrington"                , owgr: 999 },
  { espnId: "5215013" , name: "Jackson Koivun"                    , owgr: 999 },
  { espnId: "5360549" , name: "Jackson Ormond"                    , owgr: 999 },
  { espnId: "5203535" , name: "Jackson Van Paris"                 , owgr: 999 },
  { espnId: "5326067" , name: "Jake Peacock"                      , owgr: 999 },
  { espnId: "5289156" , name: "Jake Sollon"                       , owgr: 999 },
  { espnId: "4683800" , name: "James Nicholas"                    , owgr: 999 },
  { espnId: "10990"   , name: "Jimmy Stanger"                     , owgr: 999 },
  { espnId: "4894340" , name: "Kaito Onishi"                      , owgr: 999 },
  { espnId: "5362522" , name: "Logan Reilly"                      , owgr: 999 },
  { espnId: "10994"   , name: "Manav Shah"                        , owgr: 999 },
  { espnId: "7120"    , name: "Marcelo Rozo"                      , owgr: 999 },
  { espnId: "5362518" , name: "Marek Fleming"                     , owgr: 999 },
  { espnId: "5289811" , name: "Mason Howell"                      , owgr: 999 },
  { espnId: "5344763" , name: "Mateo Pulcini"                     , owgr: 999 },
  { espnId: "4390719" , name: "Matthew Jordan"                    , owgr: 999 },
  { espnId: "5362523" , name: "Matthew Robles"                    , owgr: 999 },
  { espnId: "5209798" , name: "Miles Russell"                     , owgr: 999 },
  { espnId: "10914"   , name: "Nathan Kimsey"                     , owgr: 999 },
  { espnId: "10048"   , name: "Nick Hardy"                        , owgr: 999 },
  { espnId: "4382434" , name: "Niklas Nørgaard"                   , owgr: 999 },
  { espnId: "186"     , name: "Padraig Harrington"                , owgr: 999 },
  { espnId: "5210226" , name: "Preston Stout"                     , owgr: 999 },
  { espnId: "5277550" , name: "Robbie Higgins"                    , owgr: 999 },
  { espnId: "5289692" , name: "Rocco Repetto Taylor"              , owgr: 999 },
  { espnId: "5362517" , name: "Ryder Cowan"                       , owgr: 999 },
  { espnId: "4699297" , name: "Ryuichi Oiwa"                      , owgr: 999 },
  { espnId: "4425905" , name: "Spencer Tibbits"                   , owgr: 999 },
  { espnId: "4567001" , name: "T.K. Kim"                          , owgr: 999 },
  { espnId: "4691550" , name: "Taihei Sato"                       , owgr: 999 },
  { espnId: "4372851" , name: "Taylor Montgomery"                 , owgr: 999 },
  { espnId: "4418567" , name: "Ugo Coussaud"                      , owgr: 999 },
  { espnId: "5362519" , name: "Vaughn Harber"                     , owgr: 999 },
  { espnId: "9040"    , name: "Zac Blair"                         , owgr: 999 },
];

// ─── Lookup helpers ─────────────────────────────────────────────────────

const tierLookup: Map<string, number> = new Map();
for (const g of TIER_1) tierLookup.set(g.espnId, 1);
for (const g of TIER_2) tierLookup.set(g.espnId, 2);
for (const g of TIER_3) tierLookup.set(g.espnId, 3);
for (const g of TIER_4) tierLookup.set(g.espnId, 4);

const owgrLookup: Map<string, number> = new Map();
for (const tier of [TIER_1, TIER_2, TIER_3, TIER_4]) {
  for (const g of tier) owgrLookup.set(g.espnId, g.owgr);
}

export function getTierForGolfer(espnId: string): number {
  return tierLookup.get(espnId) ?? 4;
}

export function getOwgrForGolfer(espnId: string): number {
  return owgrLookup.get(espnId) ?? 999;
}

export function getAllUsOpenPlayerIds(): Set<string> {
  return new Set(
    [...TIER_1, ...TIER_2, ...TIER_3, ...TIER_4].map((g) => g.espnId)
  );
}
